["Core.ThingCategory"]
name = "Terrain"
things = [
"Terrain_Water",
"Terrain_Mush",
"Terrain_Rich_Soil",
"Terrain_Soil",
"Terrain_Dirt",
"Terrain_Mountain"
]

["Core.ExtTerrainCategory"]
rules = [
[ { parameter = "height", operation = "<", value = 0.2 } ],
[ { parameter = "height", operation = "<", value = 0.4 }, { parameter = "moisture", operation = ">=", value = 0.75 } ],
[ { parameter = "height", operation = "<", value = 0.65 }, { parameter = "moisture", operation = ">=", value = 0.75 }, { parameter = "variety", operation = ">=", value = 0.75 } ],
[ { parameter = "height", operation = "<", value = 0.65 }, { parameter = "variety", operation = ">=", value = 0.25 } ],
[ { parameter = "height", operation = "<", value = 0.8 } ],
[ { parameter = "height", operation = ">=", value = 0.8 } ]
]